preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:
  sonatype-oss-releases:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group:
          de.robv.android.xposed
  androidx-dev:
    url: https://androidx.dev/storage/compose-compiler/repository/

plugins:
  com.android.application:
    alias: android-application
    version: 8.1.4
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 1.9.21
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 1.9.21-1.0.15

libraries:
  de.robv.android.xposed:
    api:
      version: 82
      repositories:
        rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.2.0
    ksp-xposed:
      version-ref: <this>::api
  com.github.duanhong169:
    drawabletoolbox:
      version: 1.0.7
  androidx.core:
    core-ktx:
      version: 1.12.0
  androidx.appcompat:
    appcompat:
      version: 1.6.1
  androidx.activity:
    activity-compose:
      version: 1.7.0
  androidx.lifecycle:
    lifecycle-runtime-ktx:
      version: 2.6.1
  androidx.compose:
    compose-bom:
      version: 2023.08.00
  androidx.compose.ui:
    ui:
      version: 1.5.4
    ui-graphics:
      version: 1.5.4
    ui-tooling-preview:
      version: 1.5.4
  androidx.compose.material3:
    material3:
      version: 1.1.2
  org.luckypray:
    dexkit:
      version: 2.0.0-rc8
  com.google.android.material:
    material:
      version: 1.10.0
  androidx.constraintlayout:
    constraintlayout:
      version: 2.1.4
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  junit:
    junit:
      version: 4.13.2